name: Scheduled scanning
on:
  push:
    paths:
      - .github/workflows/scheduled.yml
  schedule:
    # once per hour
    - cron: "0 * * * *"

concurrency:
  group: scheduled
  cancel-in-progress: true

jobs:
  scan:
    if: startsWith( github.repository, 'appfair/' )
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@main
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Configure appfairbot
        run: |
          git config credential.username "appfairbot"
          git config credential.password "${{ secrets.APP_FAIR_BOT_TOKEN }}"
          git config user.name "appfairbot"
          git config user.email "appfairbot@appfair.net"
      - name: Scan Artifacts
        env:
          VTAPIKEY: ${{ secrets.VTAPIKEY }}
        run: |
          scripts/scanurls.sh
          scripts/scanhashes.sh
      - name: Commit hashes
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.APP_FAIR_BOT_TOKEN }}
        run: |
          git pull -ff
          git add files
          git commit -m "Scan Hashes" files || echo "nothing to commit"
          git add urls
          git commit -m "Scan URLs" urls || echo "nothing to commit"
          git push


